[package]
name = "current"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[features]
default = ["impl-x86_64"]
impl-x86_64 = ["dep:x86_64"]
impl-mock = ["dep:arch"]

[dependencies]
x86_64 = { path = "../x86_64", optional = true }
arch = { path = "../arch", optional = true }
