[workspace]
resolver = "3"
exclude = ["crates/flanterm_rust"]
members = [
    "crates/boot",
    "crates/protocol/limine",
    "crates/arch/arch",
    "crates/arch/x86_64",
    "crates/arch/current",
    "crates/mm",
    "crates/fs",
    "crates/driver",
    "crates/loader",
    "crates/utils",
    "crates/efi",
    "crates/firmware",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
missing_safety_doc = "deny"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 2
lto = true
codegen-units = 1
strip = true